export default {
    PROPERTIES_RECEIVED: 'PROPERTIES_RECEIVED',
    PROPERTY_CREATED: 'PROPERTIES_CREATED',

    MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
    MESSAGE_CREATED: 'MESSAGE_CREATED',
    
    RECENT_TENANT_TRANSACTIONS_RECEIVED: 'RECENT_TENANT_TRANSACTIONS_RECEIVED',
    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED'
}
