export default {
    PROPERTIES_RECEIVED: 'PROPERTIES_RECEIVED',
    PROPERTY_CREATED: 'PROPERTIES_CREATED',
    TOGGLE_PROPERTY_DISPLAY_TYPE: 'TOGGLE_PROPERTY_DISPLAY_TYPE',
    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED'
}
